// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    404: typeof import('./src/view/404/index.vue')['default']
    Child: typeof import('./src/view/Provide&Inject/child.vue')['default']
    copy: typeof import('./src/view/login copy/index.vue')['default']
    DiaLog: typeof import('./src/components/DiaLog/index.vue')['default']
    Editor: typeof import('./src/view/Editor/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Father: typeof import('./src/view/FatherSon/Father.vue')['default']
    FatherSlot: typeof import('./src/view/Slot/FatherSlot.vue')['default']
    Header: typeof import('./src/layout/Header.vue')['default']
    Home: typeof import('./src/view/Home/index.vue')['default']
    ICarbonPassword: typeof import('~icons/carbon/password')['default']
    ICarbonUser: typeof import('~icons/carbon/user')['default']
    'ListWuhu!': typeof import('./src/view/TestTemplate/ListWuhu!.vue')['default']
    Login: typeof import('./src/view/Login/index.vue')['default']
    MouseTracker: typeof import('./src/view/Slot/MouseTracker.vue')['default']
    MyImg: typeof import('./src/components/ErrorImage/MyImg.vue')['default']
    'Provide&Inject': typeof import('./src/view/Provide&Inject/index.vue')['default']
    Register: typeof import('./src/view/Register/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowImages: typeof import('./src/view/ShowImages/index.vue')['default']
    Son: typeof import('./src/view/FatherSon/Son.vue')['default']
    SonSlot: typeof import('./src/view/Slot/SonSlot.vue')['default']
    TestDemo: typeof import('./src/view/TestDemo/index.vue')['default']
    Undefined: typeof import('./src/layout/index.vue')['default']
    WangEditor: typeof import('./src/components/WangEditor/index.vue')['default']
    WriteBlog: typeof import('./src/view/WriteBlog/index.vue')['default']
  }
}
